###
//INDEX
GET http://crud-esig.herokuapp.com/task

###
//GETLISTTASK done, unrealized, all
GET http://crud-esig.herokuapp.com/task/all

###
//CADASTRAR
POST http://crud-esig.herokuapp.com/task
content-type: application/json

{
    "description":"teste 7",
    "done":false,
    "filter":"unrealized"
}

###
//ATUALIZAR
PUT http://crud-esig.herokuapp.com/task/12
content-type: application/json

{   
    
    "done":false,
    "filtro":"done"
}

###
//DELETAR
DELETE http://crud-esig.herokuapp.com/task/8

###
//DELETAR CONCLUIDOS
DELETE http://crud-esig.herokuapp.com/task-done
