###
//LISTAR TASK Filtros(done, unrealized, all)
GET http://crud-esig.herokuapp.com/api/task/all

###
//CADASTRAR
POST http://crud-esig.herokuapp.com/api/task
content-type: application/json

{
    "description":"Minha primeira tarefa",
    "done":false,
    "filter":"all"
}

###
//ATUALIZAR
PUT http://crud-esig.herokuapp.com/api/task/38
content-type: application/json

{   
    "description":"Minha primeira tarefa",
    "done":true,
    "filtro":"all"
}

###
//DELETAR
DELETE http://crud-esig.herokuapp.com/api/task/8

###
//DELETAR CONCLUIDOS
DELETE http://crud-esig.herokuapp.com/api/task-done
