###
//INDEX
GET http://192.168.1.87:8000/backend/public/index.php/api/task

###
//GETLISTTASK done, unrealized, all
GET http://192.168.1.87:8000/backend/public/index.php/api/task/unrealized

###
//CADASTRAR
POST http://192.168.1.87:8000/backend/public/index.php/api/task
content-type: application/json

{
    "description":"teste 7",
    "done":false,
    "filtro":"unrealized"
}

###
//ATUALIZAR
PUT http://192.168.1.87:8000/backend/public/index.php/api/task/8
content-type: application/json

{
    "done":true,
    "filtro":"done"
}

###
//DELETAR
DELETE http://192.168.1.87:8000/backend/public/index.php/api/task/8